import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import { StoreProvider } from "../store/storeProvider";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Providers>
            <Header />
            <main className="container">{children}</main>
            <Footer />
          </Providers>
        </body>
      </html>
    </StoreProvider>
  );
}
